In [1]:
import pandas as pd
import matplotlib.pyplot as plt

In [2]:
expense_data = pd.read_excel("../expense_report.xlsx", sheet_name=None)

In [3]:
expense_data

{'Jan': Empty DataFrame
 Columns: []
 Index: [], 'Feb': Empty DataFrame
 Columns: []
 Index: [], 'March':      Txn Date Value Date                                        Description  \
 0  2020-03-02 2020-03-02     BULK POSTING-     00000007080 210220 SANGAM...
 1  2020-03-03 2020-03-03     by debit card-OTHPG 909630      ONE97 COMMU...
 2  2020-03-03 2020-03-03     TO TRANSFER-UPI/DR/006308680849/PAVITHRA/SB...
 3  2020-03-04 2020-03-04     DEBIT-ATMCard AMC  559601*7320 SILVER-GLOBAL--
 4  2020-03-05 2020-03-05     BULK POSTING-     00000007080 290220 SREE B...
 5  2020-03-09 2020-03-09  BY CLEARING / CHEQUE-CHB   BY CLEARING CHQ 243...
 6  2020-03-12 2020-03-12     BY TRANSFER-INB Payment towards loan repaym...
 7  2020-03-12 2020-03-12     TO TRANSFER-UPI/DR/007208486376/PAVITHRA/SB...
 8  2020-03-14 2020-03-14     by debit card-OTHPG 763017      APPLE.COM/B...
 9  2020-03-14 2020-03-14     TO TRANSFER-INB Payment towards loan repaym...
 10 2020-03-16 2020-03-16     TO TRANSFER-UPI/DR/007660367600/PhonePe/ICI...
 11 2020-03-16 2020-03-16     by debit card-SBIPG SU8625456503AMAZON     ...
 12 2020-03-16 2020-03-16     by debit card-SBIPG SU8625472839AMAZON     ...
 13 2020-03-16 2020-03-16     TO TRANSFER-UPI/DR/007657709186/Sri Sada/UT...
 14 2020-03-18 2020-03-18     by debit card-SBIPG SU8630872979AMAZON     ...
 15 2020-03-21 2020-03-21     TO TRANSFER-UPI/DR/008118419797/MASOOD A/HD...
 16 2020-03-22 2020-03-22     by debit card-SBIPG SU8645572869AMAZON     ...
 17 2020-03-25 2020-03-25                                 CREDIT INTEREST---
 18 2020-03-27 2020-03-27     TO TRANSFER-INB Life Insurance Corporatio L...
 19 2020-03-27 2020-03-27  BY CLEARING / CHEQUE-VJB   BY CLEARING CHQ 973...
 20 2020-03-31 2020-03-31            BY TRANSFER-INB Salary for March 2020--

                                    Ref No./Cheque No.         Debit   Credit  \
 0                                                 NaN                    1.5
 1                                                 NaN          1000
 2                           TRANSFER TO 4898827162096            50
 3                                                 NaN         147.5
 4                                                 NaN                   2.87
 5                                              243758                2957.07
 6   ITY8591161               TRANSFER FROM 3732493...                    115
 7                           TRANSFER TO 4898861162095           115
 8                                                 NaN            49
 9   ITY8853941               TRANSFER TO 540338535...   2,00,000.00
 10                          TRANSFER TO 5097509162090           411
 11                                                NaN          1104
 12                                                NaN           971
 13                          TRANSFER TO 5097531162093          1490
 14                                                NaN           379
 15                          TRANSFER TO 5099756162092         12700
 16                                                NaN           999
 17                                                NaN                   2520
 18  SSBI8657735804IGAIJVRTO3               TRANSFE...          4209
 19                                             973402                  43955
 20  CTJ071552400002          TRANSFER FROM 9856111...                  35847

         Balance
 0   5,72,407.29
 1   5,71,407.29
 2   5,71,357.29
 3   5,71,209.79
 4   5,71,212.66
 5   5,74,169.73
 6   5,74,284.73
 7   5,74,169.73
 8   5,74,120.73
 9   3,74,120.73
 10  3,73,709.73
 11  3,72,605.73
 12  3,71,634.73
 13  3,70,144.73
 14  3,69,765.73
 15  3,57,065.73
 16  3,56,066.73
 17  3,58,586.73
 18  3,54,377.73
 19  3,98,332.73
 20  4,34,179.73  , 'April':      Txn Date Value Date                                        Description  \
 0  2020-04-01 2020-04-01     BY TRANSFER-INB Payment towards loan repaym...
 1  2020-04-02 2020-04-02                          TO TRANSFER-INB ppf2020--
 2  2020-04-02 2020-04-02                          TO TRANSFER-INB ppf2020--
 3  2020-04-02 2020-04-02     by debit card-SBIPG SU8674178920AMAZON     ...
 4  2020-04-02 2020-04-02     by debit card-SBIPG SU8674183219AMAZON     ...
 5  2020-04-02 2020-04-02     BY TRANSFER- SBIPG 200402932905AMAZON      ...
 6  2020-04-09 2020-04-09     TO TRANSFER-UPI/DR/010084137093/PhonePe/YES...
 7  2020-04-09 2020-04-09     TO TRANSFER-UPI/DR/010021406458/PhonePe/YES...
 8  2020-04-13 2020-04-13     TO TRANSFER-UPI/DR/010413821590/BBMP/HDFC/b...
 9  2020-04-14 2020-04-14     TO TRANSFER-UPI/DR/010536657940/PhonePe/YES...
 10 2020-04-14 2020-04-14     by debit card-OTHPG 678187      APPLE.COM/B...
 11 2020-04-16 2020-04-16     by debit card-SBIPG SU8714723175AMAZON     ...
 12 2020-04-17 2020-04-17     by debit card-SBIPG ST8716141049AMAZON     ...
 13 2020-04-17 2020-04-17     by debit card-SBIPG SU8716172046AMAZON     ...
 14 2020-04-17 2020-04-17  CHEQUE DEPOSIT- Mr. ANDIAPELLAI  PERiyasamy to...
 15 2020-04-17 2020-04-17     TO TRANSFER-UPI/DR/010816714151/PRAVEEN /CO...
 16 2020-04-22 2020-04-22        TO TRANSFER-INB INDLOCAL SOLUTIONS PVT LT--
 17 2020-04-26 2020-04-26     by debit card-OTHPOS501154      ASHA SWEET ...

                                    Ref No./Cheque No.         Debit  \
 0   ITZ0118993               TRANSFER FROM 3732493...
 1   IF23212012               TRANSFER TO 373076117...   1,50,000.00
 2   IF23213019               TRANSFER TO 540338886...   1,50,000.00
 3                                                 NaN           380
 4                                                 NaN           348
 5                         TRANSFER FROM 2399465042921
 6                           TRANSFER TO 5097792162094           399
 7                           TRANSFER TO 4898283162091           399
 8                           TRANSFER TO 5097530162093          6759
 9                           TRANSFER TO 5097620162092            49
 10                                                NaN            49
 11                                                NaN           903
 12                                                NaN           456
 13                                                NaN          1244
 14  TRANSFER TO 54033853530                       ...
 15                          TRANSFER TO 5097957162099          1700
 16  10224384809IGAIMTNLH0               TRANSFER T...           420
 17                                                NaN            88

          Credit      Balance
 0           500  4,34,679.73
 1                2,84,679.73
 2                1,34,679.73
 3                1,34,299.73
 4                1,33,951.73
 5           380  1,34,331.73
 6                1,33,932.73
 7                1,33,533.73
 8                1,26,774.73
 9                1,26,725.73
 10               1,26,676.73
 11               1,25,773.73
 12               1,25,317.73
 13               1,24,073.73
 14  1,50,000.00  2,74,073.73
 15               2,72,373.73
 16               2,71,953.73
 17               2,71,865.73  , 'May':      Txn Date Value Date                                        Description  \
 0  2020-05-01 2020-05-01            BY TRANSFER-INB Salary for April 2020--
 1  2020-05-02 2020-05-02     by debit card-SBIPG SU8759887445AMAZON     ...
 2  2020-05-07 2020-05-07     BY TRANSFER-UPI/CR/012809643321/Mr Ravee/ID...
 3  2020-05-07 2020-05-07     TO TRANSFER-INB BSNL                      B...
 4  2020-05-07 2020-05-07     by debit card-OTHPOS507800      ASHA SWEET ...
 5  2020-05-09 2020-05-09     TO TRANSFER-UPI/DR/013036711104/MRAJU/CORP/...
 6  2020-05-10 2020-05-10     by debit card-OTHPG 030187      AliExpress....
 7  2020-05-10 2020-05-10     by debit card-OTHPG 421209      GOOGLE CLOU...
 8  2020-05-10 2020-05-10     by debit card-OTHPG 421210      GOOGLE CLOU...
 9  2020-05-12 2020-05-12             BY TRANSFER-INB Refund of IGAIOMXZN0--
 10 2020-05-13 2020-05-13     DEBIT-     00000007080INT surcharge/tips dt...
 11 2020-05-14 2020-05-14     TO TRANSFER-UPI/DR/013540476840/PhonePe/YES...
 12 2020-05-16 2020-05-16     TO TRANSFER-UPI/DR/013754927616/BharatPe/YE...
 13 2020-05-16 2020-05-16     by debit card-SBIPG SU8802180525AMAZON     ...
 14 2020-05-16 2020-05-16     by debit card-SBIPG SU8802277721AMAZON     ...
 15 2020-05-16 2020-05-16     by debit card-SBIPG SU8802280774AMAZON     ...
 16 2020-05-17 2020-05-17     by debit card-SBIPG ST8803012337BSNLPOST   ...
 17 2020-05-18 2020-05-18             BY TRANSFER-INB Refund of IGAIMTNLH0--
 18 2020-05-23 2020-05-23     BULK POSTING-     00000007080 100520 GOOGLE...
 19 2020-05-23 2020-05-23     BULK POSTING-     00000007080 100520 GOOGLE...
 20 2020-05-26 2020-05-26     by debit card-SBIPG SU8832783945AMAZON     ...
 21 2020-05-26 2020-05-26     BY TRANSFER- SBIPG 200526492384AMAZON      ...
 22 2020-05-29 2020-05-29              BY TRANSFER-INB Salary for May 2020--

                                    Ref No./Cheque No.         Debit Credit  \
 0   CTJ299621800002          TRANSFER FROM 9856111...                27016
 1                                                 NaN            48
 2                         TRANSFER FROM 5099046162099                  700
 3   SSBI8773410254IGAIOMXZN0               TRANSFE...           699
 4                                                 NaN           270
 5                           TRANSFER TO 5098049162093           650
 6                                                 NaN       1116.45
 7                                                 NaN             1
 8                                                 NaN             1
 9   SSBI87734102541IXGASYNYW3               TRANSF...                  699
 10                                                NaN          4.59
 11                          TRANSFER TO 5097810162096            49
 12                          TRANSFER TO 5098006162093           527
 13                                                NaN          1432
 14                                                NaN           801
 15                                                NaN          1403
 16                                                NaN           699
 17  102243848096964802621IXGASZKXW7               ...                  420
 18                                                NaN                    1
 19                                                NaN                    1
 20                                                NaN         16999
 21                        TRANSFER FROM 2399465042921                16999
 22  CTJ554762800002          TRANSFER FROM 9856111...                35847

         Balance
 0   2,98,881.73
 1   2,98,833.73
 2   2,99,533.73
 3   2,98,834.73
 4   2,98,564.73
 5   2,97,914.73
 6   2,96,798.28
 7   2,96,797.28
 8   2,96,796.28
 9   2,97,495.28
 10  2,97,490.69
 11  2,97,441.69
 12  2,96,914.69
 13  2,95,482.69
 14  2,94,681.69
 15  2,93,278.69
 16  2,92,579.69
 17  2,92,999.69
 18  2,93,000.69
 19  2,93,001.69
 20  2,76,002.69
 21  2,93,001.69
 22  3,28,848.69  , 'June':      Txn Date Value Date                                        Description  \
 0  2020-06-01 2020-06-01     by debit card-SBIPG SU8854775003AMAZON     ...
 1  2020-06-03 2020-06-03     by debit card-SBIPG SU8859121662AMAZON     ...
 2  2020-06-17 2020-06-17     by debit card-SBIPG SU8905702127AMAZON     ...
 3  2020-06-17 2020-06-17     TO TRANSFER-UPI/DR/016910135690/billdesk/IC...
 4  2020-06-17 2020-06-17     TO TRANSFER-UPI/DR/016910156722/billdesk/IC...
 5  2020-06-22 2020-06-22     BY TRANSFER-UPI/CR/017323868094/VIJITHA /HD...
 6  2020-06-24 2020-06-24     BY TRANSFER-UPI/CR/017611745610/GOOGLEPAY/U...
 7  2020-06-25 2020-06-25     BY TRANSFER-UPI/CR/017716836633/GOOGLEPAY/U...
 8  2020-06-25 2020-06-25                                 CREDIT INTEREST---
 9  2020-06-27 2020-06-27     by debit card-OTHPOS663388      AMPLE TECHN...
 10 2020-06-28 2020-06-28     TO TRANSFER-UPI/DR/018011078031/PRAVEEN /CO...
 11 2020-06-28 2020-06-28     TO TRANSFER-UPI/DR/018012117508/Falcon C/SB...
 12 2020-06-28 2020-06-28     by debit card-SBIPG SU8941112039AMAZON     ...
 13 2020-06-28 2020-06-28     BY TRANSFER- SBIPG 200628188919AMAZON      ...
 14 2020-06-28 2020-06-28     TO TRANSFER-UPI/DR/018018357686/Falcon C/SB...
 15 2020-06-30 2020-06-30     TO TRANSFER-UPI/DR/018207080348/PAVITHRA/SB...

              Ref No./Cheque No.         Debit Credit      Balance
 0                           NaN         26999         3,01,849.69
 1                           NaN          4500         2,97,349.69
 2                           NaN          1149         2,96,200.69
 3     TRANSFER TO 4898740162092           411         2,95,789.69
 4     TRANSFER TO 5097696162094          1527         2,94,262.69
 5   TRANSFER FROM 4898936162092                   10  2,94,272.69
 6   TRANSFER FROM 5098987162096                  125  2,94,397.69
 7   TRANSFER FROM 4898967162096                   15  2,94,412.69
 8                           NaN                 1926  2,96,338.69
 9                           NaN          8500         2,87,838.69
 10    TRANSFER TO 4897686162092           100         2,87,738.69
 11    TRANSFER TO 4898932162096           500         2,87,238.69
 12                          NaN          6499         2,80,739.69
 13  TRANSFER FROM 2399465042921                 6499  2,87,238.69
 14    TRANSFER TO 5098130162090           100         2,87,138.69
 15    TRANSFER TO 5097663162093          3000         2,84,138.69  , 'July':      Txn Date Value Date                                        Description  \
 0  2020-07-01 2020-07-01             BY TRANSFER-INB Salary for June 2020--
 1  2020-07-01 2020-07-01     BY TRANSFER-INB Payment towards loan repaym...
 2  2020-07-01 2020-07-01     TO TRANSFER-UPI/DR/018322668511/VIJITHA /HD...
 3  2020-07-02 2020-07-02     TO TRANSFER-UPI/DR/018448944883/PhonePe/YES...
 4  2020-07-02 2020-07-02     BY TRANSFER-INB Payment towards loan repaym...
 5  2020-07-03 2020-07-03     by debit card-SBIPG SU8959809125AMAZON     ...
 6  2020-07-06 2020-07-06     TO TRANSFER-UPI/DR/018816459110/Gadgets /UT...
 7  2020-07-14 2020-07-14     TO TRANSFER-UPI/DR/019616126964/SELVARAJ/KK...
 8  2020-07-14 2020-07-14     BY TRANSFER-UPI/CR/019616694142/GOOGLEPAY/U...
 9  2020-07-20 2020-07-20     by debit card-SBIPG SU9017914579AMAZON     ...
 10 2020-07-20 2020-07-20     BY TRANSFER-INB Payment towards loan repaym...
 11 2020-07-20 2020-07-20     by debit card-OTHPOS024587      MAHAVEER ME...
 12 2020-07-24 2020-07-24     by debit card-SBIPG SU9034296147AMAZON     ...
 13 2020-07-24 2020-07-24     by debit card-SBIPG SU9034304531AMAZON     ...
 14 2020-07-24 2020-07-24     by debit card-SBIPG SU9034283476AMAZON     ...
 15 2020-07-28 2020-07-28     TO TRANSFER-UPI/DR/020922493060/mysundir/UT...
 16 2020-07-28 2020-07-28     TO TRANSFER-UPI/DR/021014233448/CHARLES S/F...
 17 2020-07-30 2020-07-30             BY TRANSFER-INB Salary for July 2020--
 18 2020-07-31 2020-07-31     by debit card-OTHPOS014546      BUY N SAVE ...
 19 2020-07-31 2020-07-31     BULK POSTING-     00000007080 290720 ALIEXP...

                                    Ref No./Cheque No.         Debit   Credit  \
 0   CTJ903149800002          TRANSFER FROM 9856111...                  40847
 1   ITZ7933426               TRANSFER FROM 3732493...                   3000
 2                           TRANSFER TO 4898847162092            10
 3                           TRANSFER TO 5097826162099           599
 4   ITZ8056368               TRANSFER FROM 3732493...                    600
 5                                                 NaN           498
 6                           TRANSFER TO 5097551162099          4999
 7                           TRANSFER TO 5099453162096           700
 8                         TRANSFER FROM 5098924162090                      5
 9                                                 NaN           598
 10  IT000BYGY9               TRANSFER FROM 3732493...                    600
 11                                                NaN           200
 12                                                NaN           950
 13                                                NaN          1449
 14                                                NaN           411
 15                          TRANSFER TO 5097539162095            25
 16                          TRANSFER TO 4898832162099         10500
 17  CTK220380800002          TRANSFER FROM 9856111...                  35847
 18                                                NaN           133
 19                                                NaN                1107.37

         Balance
 0   3,24,985.69
 1   3,27,985.69
 2   3,27,975.69
 3   3,27,376.69
 4   3,27,976.69
 5   3,27,478.69
 6   3,22,479.69
 7   3,21,779.69
 8   3,21,784.69
 9   3,21,186.69
 10  3,21,786.69
 11  3,21,586.69
 12  3,20,636.69
 13  3,19,187.69
 14  3,18,776.69
 15  3,18,751.69
 16  3,08,251.69
 17  3,44,098.69
 18  3,43,965.69
 19  3,45,073.06  , 'August':      Txn Date Value Date                                        Description  \
 0  2020-08-01 2020-08-01     BY TRANSFER-UPI/CR/021403893755/GOOGLEPAY/U...
 1  2020-08-07 2020-08-07     by debit card-SBIPOS002661345783FUTURE VALU...
 2  2020-08-08 2020-08-08     TO TRANSFER-UPI/DR/022117474978/DEEPAK S/PU...
 3  2020-08-08 2020-08-08     TO TRANSFER-UPI/DR/022117558460/PRAVEEN /SY...
 4  2020-08-12 2020-08-12     by debit card-OTHPOS566126      MAHA BAZAAR...
 5  2020-08-15 2020-08-15     TO TRANSFER-UPI/DR/022820794134/PhonePe/YES...
 6  2020-08-17 2020-08-17     by debit card-SBIPG SU9125436594AMAZON     ...
 7  2020-08-17 2020-08-17     by debit card-SBIPG SU9125470350AMAZON     ...
 8  2020-08-17 2020-08-17     TO TRANSFER-UPI/DR/023021366371/billdesk/IC...
 9  2020-08-18 2020-08-18     TO TRANSFER-UPI/DR/023110834986/SUN DIRE/HD...
 10 2020-08-18 2020-08-18     TO TRANSFER-UPI/DR/023110845447/SUN DIRE/HD...

              Ref No./Cheque No.         Debit Credit      Balance
 0   TRANSFER FROM 5098686162098                    5  3,45,078.06
 1                           NaN            85         3,44,993.06
 2     TRANSFER TO 5098027162099         38000         3,06,993.06
 3     TRANSFER TO 5099722162092            20         3,06,973.06
 4                           NaN           225         3,06,748.06
 5     TRANSFER TO 4898751162090          1203         3,05,545.06
 6                           NaN           707         3,04,838.06
 7                           NaN          1203         3,03,635.06
 8     TRANSFER TO 5097519162099          1687         3,01,948.06
 9     TRANSFER TO 5097626162097          1352         3,00,596.06
 10    TRANSFER TO 5097607162099            50         3,00,546.06  }

In [4]:
df = expense_data['March']
df.describe()

c:\users\arun\appdata\local\programs\python\python36\lib\site-packages\ipykernel_launcher.py:2: FutureWarning: Treating datetime data as categorical rather than numeric in `.describe` is deprecated and will be removed in a future version of pandas. Specify `datetime_is_numeric=True` to silence this warning and adopt the future behavior now.

c:\users\arun\appdata\local\programs\python\python36\lib\site-packages\ipykernel_launcher.py:2: FutureWarning: Treating datetime data as categorical rather than numeric in `.describe` is deprecated and will be removed in a future version of pandas. Specify `datetime_is_numeric=True` to silence this warning and adopt the future behavior now.

,Txn Date,Value Date,Description,Ref No./Cheque No.,Debit,Credit,Balance
count,21,21,21,11.0,21,21,21
unique,14,14,21,11.0,15,8,20
top,2020-03-16 00:00:00,2020-03-16 00:00:00,BY TRANSFER-INB Payment towards loan repaym...,243758.0,,,"5,74,169.73"
freq,4,4,1,1.0,7,14,2
first,2020-03-02 00:00:00,2020-03-02 00:00:00,NaN,NaN,NaN,NaN,NaN
last,2020-03-31 00:00:00,2020-03-31 00:00:00,NaN,NaN,NaN,NaN,NaN

In [5]:
df.plot(kind='bar', x='Debit', y='Balance', color='red')
plt.show() # not working

KeyError: 'Debit'

In [7]:
df.columns

Index(['Txn Date', 'Value Date', 'Description', 'Ref No./Cheque No.',
       '        Debit', 'Credit', 'Balance'],
      dtype='object')

In [8]:
df.plot(kind="bar",
        x="Balance",
        y="Txn Date")

ValueError: view limit minimum 0.0 is less than 1 and is an invalid Matplotlib date value. This often happens if you pass a non-datetime value to an axis that has datetime units

In [ ]:
df.plot()